### ISSUE TITLE
support Parse.Relation

### ISSUE THREAD

**Issue by yutin1987** [HustleInc/parse-mockdb#11]
when use
```
const qService = new Parse.Query('Service');
qService
  .get(id)
  .then((service) => {
    const qMember = service.relation('member').query();
    return qMember.find()
  });
```

Error Message
```
Type Error: Cannot read property 'object' of undefined
  at node_modules/parse-mockdb/src/parse-mockdb.js:501:64
```

console.log(qMember);
```
ParseQuery {
  classNmae: 'Member',
  where: {'$relatedTo': {object: [Object], key: 'member'}
  _include: [],
  _limit: -1,
  _skip: 0,
  _extraOptions: {}
}
```

parse-mockdb is a nice repository :100:

**Comment by fatuhoku** [comment]
Just to add to this issue, I want `Parse.Relation` support for testing my checks against `Parse.Role`s.

I ran into trouble trying to implement the fix though. I need queries with `$eq` to work against members of a relation (it's legal, and works against the backend, believe it or not!).

However, the only way to evaluate the members of a relation is to use `query`, as @yutin1987 mentions above. This is not necessarily treated in the same way as an array of Pointers and therefore requires special handling. I managed to write up a simple test:

```js
  context('Parse.Role support', function() {

    it("saves and finds role", function(done) {
      var acl = new Parse.ACL({});
      var role = new Parse.Role('Admin', acl);
      console.log('role: '+ JSON.stringify(role));
      role.save().done(function(role) {
        assert(role.get('name'));
        done();
      })
    });

    it("should retrieve relation correctly", function(done) {
      // Given
      var acl = new Parse.ACL({});
      new Parse.Role('Admin', acl).save().done(function() {
        return new Parse.User().save();
      }).done(function(savedUser) {

        // When

        // NB: using equalTo & notEqualTo here to match against members of relation.
        // See http://stackoverflow.com/a/32544695/590767
        var registeredRoleQuery = new Parse.Query(Parse.Role);
        registeredRoleQuery.equalTo('name', 'Admin');
        registeredRoleQuery.equalTo('users', savedUser);
        return registeredRoleQuery.first();

      }).done(function (registeredRole) {
        registeredRole.should.not.be.nil();
        done();
      });
    });

  });
```

**Comment by yutin1987** [comment]
@fatuhoku Parse.Role using equalTo & notEqualTo, it is work.
test ref. https://github.com/yutin1987/parse-mockdb/blob/develop/test/test.js#L1012
Thank you for your comment

**Comment by TylerBrock** [comment]
Thanks guys, I wound up implementing this myself in 3c8609f5f67532291cc0e4f9cd6443762a44cbbd and wound up going another route. I might take some of your excellent tests though.
