### ISSUE TITLE
Push version 0.1.0 to npm

### ISSUE THREAD

**Issue by fatuhoku** [HustleInc/parse-mockdb#2]
I blindly followed the README and ran tests to get:

```node
  48) ParseMock when object has beforeSave hook registered rejects the save if there is a problem:
     Error: You need to call Parse.initialize before using Parse.
      at Context.<anonymous> (test.js:828:13)
```

Only then did I realise `npm_modules` contained 0.0.3 and not the latest 0.1.0.

**Comment by TylerBrock** [comment]
Yup, waiting to deploy 0.1.0, need to get package transferred to me. Hold tight.

**Comment by TylerBrock** [comment]
It's deployed, do you want to give it a whirl?

**Comment by TylerBrock** [comment]
Remember to run `npm update parse-mockdb` as well as ensure you are using version 1.6.0 or higher of the Parse JS SDK.

**Comment by fatuhoku** [comment]
Nice one :beers:

Trying to run example test file ... updating node...
