### ISSUE TITLE
Upgrade to lodash 4.0

### ISSUE THREAD

**Issue by fatuhoku** [HustleInc/parse-mockdb#20]
Just tried upgrading — but tests fail because the following methods were removed

 - `_.all`
 - `_.any`

... and after that, 5 test are broken.

**Comment by TylerBrock** [comment]
Ok, feel free to make a pull request. Should be ok with NPM 3x and not cause any conflicts.

**Comment by TylerBrock** [comment]
@fatuhoku thanks for reporting, we are going to start requiring 1.7.x shortly so there will be some additional changes.

**Comment by fatuhoku** [comment]
Okay, I've just made fixes — it's all because their counterparts,  `_.every`, capture `this`.

I can submit a pull request, but it'll be stacked on top of all the other ones too!

**Comment by TylerBrock** [comment]
Ah sorry, I was just like, ehhh i'll just do it. I didn't see you were also taking a stab at it.

**Comment by fatuhoku** [comment]
@TylerBrock No worries — your fix was better. I ended up trying to do horrible `var arg0 = this;` business everywhere!

**Comment by fatuhoku** [comment]
@TylerBrock The build is broken!!!!!!!!!!
