### ISSUE TITLE
Support for setting `createdAt` and `updatedAt` fields for finer control over test data

### ISSUE THREAD

**Issue by fatuhoku** [HustleInc/parse-mockdb#22]
I'm writing a time-sensitive algorithm that uses `createAt` in order to filter away newer records and process only older records.

However when I tried to create test rows that look like they were created in the past, I found I couldn't. I couldn't use `.set()` afterwards to mutate that field either.

**Comment by TylerBrock** [comment]
Hrm, that should work, can you put up a simple test case that breaks?

We are setting createdAt when we create the objects and updating updated at when we update them as far as I know.

**Comment by TylerBrock** [comment]
I'm running into this now... thanks for reporting it 2 months ago, hah!

**Comment by TylerBrock** [comment]
Fixed in #85695c8737b321725f44a18f57f3d025ab87320d
