### ISSUE TITLE
Unit test eating assertion fails....

### ISSUE THREAD

**Issue by acinader** [HustleInc/parse-mockdb#30]
Hi @TylerBrock,

i'm continuing to investigate #27, and i have a pr coming up real soon, but wanted to get your feedback on a question.

As part of digging into my most recent change and why it broke my tests, I was wondering why the tests didn't fail on parse-mockdb.  I then added a test that should have failed, but it didn't, ok.  That's when I noticed that the test wasn't using done().  Ok.  Fixed that, but then I see that when an assertion in a promise fails, it doesn't get caught by the test runner.

I created a branch to show what I mean. https://github.com/acinader/parse-mockdb/commit/292fa00eed7016f4947232c26ce7c209b4879ae5

In any event, it seems to me that Parse.Promise and mocha don't play well together.  Have you noticed what I am talking about?

I'm game to give it some thought, but before I waste our time, I figured I'd ask if this is in any way on your radar screen?

**Comment by acinader** [comment]
or am i just doing something completely wrong?

**Comment by TylerBrock** [comment]
I think we got to the bottom of this, yeah?

**Comment by acinader** [comment]
nope :(

here's a branch i made to show what i mean https://github.com/acinader/parse-mockdb/tree/unit-test-madness  see this commit: https://github.com/acinader/parse-mockdb/commit/292fa00eed7016f4947232c26ce7c209b4879ae5

seems to me like it is something with parse promises?  but maybe its just something I am doing wrong.  I can investigate it further, but wanted to see if you're seeing the same behavior.

**Comment by acinader** [comment]
ok, i think i get it now, if fixed my branch with this commit: 788c9c5a

which I got from reading this: https://www.sitepoint.com/promises-in-javascript-unit-tests-the-definitive-guide/

the fix is to  don't use 'done', instead return the promise so mocha can handle.
