### ISSUE TITLE
Any interest in linting?

### ISSUE THREAD

**Issue by acinader** [HustleInc/parse-mockdb#37]
I configured eslint to check for ```function ()``` and also for missing ```;```.

If there's any interest, I can set it up using custom rules, or a standard set like google or airbnb and then conform and get all to pass.

I'd add a dev dependency to eslint, and i'd edit package.json to include a lint sript. 

eslint can be configured in package.json.

I simply chose eslint over jshint because the first thing i googled sounded convincing, but have invested little in it, so glad to change to a preferred tool?

**Comment by TylerBrock** [comment]
Definitely! eslint is the way to go, we use airbnb style for our other code so i'm partial to that standard.

**Comment by acinader** [comment]
will do
