### ISSUE TITLE
npm link oddness?

### ISSUE THREAD

**Issue by acinader** [HustleInc/parse-mockdb#43]
ugh.  I'm trying to ```npm link``` my local parse-mockdb repo, but getting odd error, and I am curious if this is a known issue, or if I can get some help.

1. I have verified that the hash installed by ```npm install parse-mockdb``` is the same as the HEAD of my local repo.  And ```npm test``` in my project works!

1. I create the link with ```npm link ../parse-mockdb``` 

1. now when i run ```npm test``` in my project, I get this error:

```
Failed: Error: You need to call Parse.initialize before using Parse.,Error: You need to call Parse.initialize before using Parse.
  Stack:
    Error: Failed: Error: You need to call Parse.initialize before using Parse.,Error: You need to call Parse.initialize before using Parse.
        at /Users/arthur/code/Epic-Cloud/spec/feedItemSpec.js:73:35
        at Array.wrappedRejectedCallback (/Users/arthur/code/Epic-Cloud/node_modules/parse/lib/node/ParsePromise.js:160:25)
        at ParsePromise.reject (/Users/arthur/code/Epic-Cloud/node_modules/parse/lib/node/ParsePromise.js:95:35)
        at Array.wrappedRejectedCallback (/Users/arthur/code/Epic-Cloud/node_modules/parse/lib/node/ParsePromise.js:181:19)
```

Any ideas?

**Comment by TylerBrock** [comment]
Is the version of parse in your project newer than what the package.json of parse-mockdb supports?

**Comment by acinader** [comment]
so it works for you?

they were on diff versions: my proj: 1.9 my parse-mockdb repo: 1.8.5.  But i put them both at 1.8.5, and no change.

then i blew away both node_modules dirs, re npm installed.  they both get 1.9.  npm test works in both.  create link and same error :(  thanks for the idea though.

**Comment by acinader** [comment]
yeah you're right, it is the different versions.
