### ISSUE TITLE
MockDB inappropriately accepts equalTo for array columns

### ISSUE THREAD

**Issue by noahsilas** [HustleInc/parse-mockdb#52]
Given a model `MyModel` with a column `tags` containing an array of pointers to a `Tag` model:

Parse Server:

```
  var q = new Parse.Query(MyModel);
  q.equalTo('tags', [tag])
  q.find().fail(err => console.log(err))
```

results in this error:

```
  ParseError {
    code: 107,
    message: 'You cannot use [object Object] as a query parameter.' }
```

MockDB finds and returns the matching objects.

**Comment by TylerBrock** [comment]
Ooh, nice find, we see that sometimes in production.
