### ISSUE TITLE
"XMLHttpRequest failed" in jest but not mocha

### ISSUE THREAD

**Issue by charleskoehl** [HustleInc/parse-mockdb#69]
I realize this may not be directly related to parse-mockdb, but I've spent a day on this and narrowed it way down and was wondering if you could give me any insight. It's as if jest is interfering with parse-mockdb's mocking of the REST controller. The jest tests were working until today. I have tried reverting to earlier versions of my repo where they were working, but I still get the errors. (I removed node_modules and reinstalled each time I reverted.)

I've written two very simple tests files, one using mocha and the other jest. There are no special configs for mocha or jest. Both use parse/node. Strangely, if I remove the Parse.initialize call from the mocha test, it still works, but in the jest test I get the usual complaint from Parse.

This is the mocha version, which I simply run with "mocha <filename>"
```javascript
'use strict'

import Parse from 'parse/node'
import ParseMockDB from 'parse-mockdb'

Parse.initialize('test')

describe('parse-mockdb testing', () => {
  
  it('should save correctly', () => {
    ParseMockDB.mockDB(); // Mock the Parse RESTController
    let
      TheObj = Parse.Object.extend('TheParseObj'),
      obj = new TheObj()
    obj.save({message:'hello'})
      .then(obj => {
        assert.equal(obj.get('message'), 'hello');
        ParseMockDB.cleanUp(); // Clear the Database
        ParseMockDB.unMockDB(); // Un-mock the Parse RESTController
      })
  }
  )
})
```
The output for the mocha test:
```
  parse-mockdb testing
    ✓ should save correctly

  1 passing (21ms)
```

This is the jest version, which I simply run with "jest <filename>"
```javascript
'use strict'

import Parse from 'parse/node'
import ParseMockDB from 'parse-mockdb'

Parse.initialize('test')

describe('parse-mockdb testing', () => {
  
  test('should save correctly', () => {
    expect.assertions(1)
    ParseMockDB.mockDB(); // Mock the Parse RESTController
    let
      TheObj = Parse.Object.extend('TheParseObj'),
      obj = new TheObj()
    return obj.save({message:'hello'})
      .then(obj => {
        expect(obj.get('message')).toBeDefined()
        ParseMockDB.cleanUp(); // Clear the Database
        ParseMockDB.unMockDB(); // Un-mock the Parse RESTController
      })
  })
})
```
The output for the jest test (after a 5-second wait):
```
  parse-mockdb testing
    ✕ should save correctly (4593ms)

  ● parse-mockdb testing › should save correctly

    Error
      Failed: XMLHttpRequest failed: "Unable to connect to the Parse API"

  ● parse-mockdb testing › should save correctly

    expect.assertions(1)

    Expected one assertion to be called but received zero assertion calls.

      at extractExpectedAssertionsErrors (node_modules/expect/build/extract_expected_assertions_errors.js:46:19)
          at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)

Test Suites: 1 failed, 1 total
Tests:       1 failed, 1 total
Snapshots:   0 total
Time:        5.476s
```

I debugged both files in Webstorm, adding breakpoints in the MockRESTController and mockDB functions in node_modules/parse-mockdb/src/parse-mockdb.js (see screenshot below). When I ran the debugger, it stopped at both breakpoints in the mocha version, but only at the mockDb breakpoint in the jest version.

![screenshot at oct 20 21-07-28](https://user-images.githubusercontent.com/887025/31849246-6b2b1c1e-b5db-11e7-8acc-ea8f09b9345a.png)

**Comment by charleskoehl** [comment]
I also double-checked that simply running your usage example with a simple save works in node on my machine and another Mac:

1. Create file 'parse-mockdb-test.js':
```
'use strict';
const Parse = require('parse/node');
const ParseMockDB = require('parse-mockdb');

ParseMockDB.mockDB(); // Mock the Parse RESTController

// Perform saves, queries, updates, deletes, etc... using the Parse JS SDK
const
  TheObj = Parse.Object.extend('TheParseObj'),
  obj = new TheObj()

return obj.save({message:'hello'})
  .then(obj => {
    console.log(obj.get('message'))
    ParseMockDB.cleanUp(); // Clear the Database
    ParseMockDB.unMockDB(); // Un-mock the Parse RESTController
  })
```
2. Then run it with node:
```
$ node parse-mockdb-test.js'
hello
```

**Comment by ben-eb** [comment]
@charleskoehl There shouldn't be any need to call `Parse.initialize` as you don't want to connect to any server whilst using parse-mockdb. I use the following test setup with Jest and it works well:

```js
// Ensure that Parse is defined for cloud code.
const Parse = global.Parse = require('parse');
const ParseMockDB = require('parse-mockdb');

const TestObject = Parse.Object.extend('TestObject');

beforeEach(() => {
  ParseMockDB.mockDB();
  // You may also want to call registerHook here when testing beforeSave etc
});

afterEach(() => {
  ParseMockDB.cleanUp();
  ParseMockDB.unMockDB();
});

test('hook', () => {
  return new TestObject({ foo: 'bar' })
    .save()
    .then(obj => {
      expect(obj.get('foo')).toEqual('bar');
    });
});
```

My cloud functions are tested without the Parse wrappers, so for instance a `beforeSave` method might look like this:

```js
module.exports = (request, response) => {
  response.success(request.object);
};
```

This is then consumed via the main cloud code, this part is not under test as it doesn't really need to be (only test your code, not library code):

```js
Parse.Cloud.beforeSave('TestObject', require('./TestObject/beforeSave'));
```
